# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cryptobook' do
  use_frameworks!

  # Pods for Cryptobook

  pod 'Alamofire', '4.6.0'
  pod 'SwiftyJSON'

  target 'CryptobookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptobookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
