# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cryptobook' do
  use_frameworks!

  # Pods for Cryptobook

  pod 'Alamofire', '5.0.0-beta.6'

  target 'CryptobookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptobookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
